development:
  adapter: postgresql
  database: db/vavilop-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/vavilop-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/vavilop-production
  pool: 5
  timeout: 5000
